# Generated by Django 5.2.7 on 2025-10-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Senior', 'Senior'), ('Junior', 'Junior'), ('Student', 'Student'), ('Single', 'Single')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('availability', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Caddies',
            },
        ),
    ]
